# docker-compose.yml
version: '3.8'

services:
  casino-scraper:
    build: .
    container_name: casino-scraper
    restart: unless-stopped
    
    environment:
      - TZ=Asia/Manila
      - MAX_PAGES_PER_CASINO=5
      - PYTHONUNBUFFERED=1
    
    volumes:
      - ./output:/app/output
      - ./logs:/app/logs
      - ./archive:/app/archive
      - ./casino_scraper.py:/app/casino_scraper.py
    
    # deploy:
    #   resources:
    #     limits:
    #       cpus: '2'
    #       memory: 2G
    #     reservations:
    #       cpus: '1'
    #       memory: 1G
    
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  # Optional: Web dashboard
  dashboard:
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: scraper-dashboard
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./output:/usr/share/nginx/html/output:ro
      - ./logs:/usr/share/nginx/html/logs:ro
    depends_on:
      - casino-scraper